# Generated by Django 4.2.16 on 2024-09-05 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(default='2000-01-01')),
                ('dishes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dishes.dishesmodel')),
            ],
        ),
    ]
